### PR TITLE
 [Issue #59] Windows 10 Mobile ole32.dll error when playing

### PR DESCRIPTION
**Pull request by kamenlitchev**
Fix errors for native call of PropVariantClear reported in #59 . Also up Windows 10 Demo max tested version to latest Windows 10 SDK (1511).

### CODE REVIEW

**Comment by kamenlitchev** [comment]
Note - PropVariantClear for Windows 8 is changed to api-ms-win-core-com-l1-1-0.dll while Windows 8.1 should use api-ms-win-core-com-l1-1-1.dll

Not sure if it's not better to leave the dll import to ole32.dll instead for Windows 8 and implement the change

**Comment by markheath** [comment]
soory for delay, will hopefully get round to testing this soon. I've got some more UWP fixes of my own I need to merge this with

**Comment by kamenlitchev** [comment]
Thanks :) Shall I return the original "ole32.dll" for Windows 8? And leave the change only for Windows 10?

**Comment by markheath** [comment]
I have to confess I'm not sure what the best option is. Does `[DllImport("api-ms-win-core-com-l1-1-0.dll")]` only work on 8 or can it work on 8.1 too? To be honest the UWP is probably the most important thing going forwards, but if it's not too hard to keep the Win8 one working on all platforms then that would be a good idea.

**Comment by kamenlitchev** [comment]
Done. I have reverted Win8 to include the .NET PropVariantNative "ole32.dll" reference. Just to be on the safe side.

**Pull request merged**
