### PR TITLE
CoreAudioAPI extending with demo

### PR DESCRIPTION
**Pull request by KvanTTT**
Unfortunately can not check Windows Store assembly WACK.
Changes not break any functionality in existing NAudio code.

### CODE REVIEW

**Comment by markheath** [comment]
great, thanks for moving this over to GitHub. I'll try it through WACK, and also see what happens in Vista.

**Comment by markheath** [comment]
OK, works for me in Win 7 but quickly tested on Vista, and we get an access violation exception.

    System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
       at NAudio.CoreAudioApi.Interfaces.IAudioSessionManager.RegisterSessionNotification(IAudioSessionNotification sessionNotification)
       at NAudio.CoreAudioApi.AudioSessionManager.RefreshSessions() in d:\Code\github\NAudio\NAudio\CoreAudioApi\AudioSessionManager.cs:line 104
       at NAudio.CoreAudioApi.AudioSessionManager..ctor(IAudioSessionManager audioSessionManager) in d:\Code\github\NAudio\NAudio\CoreAudioApi\AudioSessionManager.cs:line 43
       at NAudio.CoreAudioApi.MMDevice.GetAudioSessionManager() in d:\Code\github\NAudio\NAudio\CoreAudioApi\MMDevice.cs:line 84
       at NAudio.CoreAudioApi.MMDevice.get_AudioSessionManager() in d:\Code\github\NAudio\NAudio\CoreAudioApi\MMDevice.cs:line 140
       at NAudioDemo.VolumeMixerDemo.VolumeMixerPanel.DeviceVolumePanel_DeviceChanged(Object sender, Object e) in d:\Code\github\NAudio\NAudioDemo\VolumeMixerDemo\VolumeMixerPanel.cs:line 56
       at NAudioDemo.VolumeMixerDemo.VolumePanel.cmbDevice_SelectedIndexChanged(Object sender, EventArgs e) in d:\Code\github\NAudio\NAudioDemo\VolumeMixerDemo\VolumePanel.cs:line 159
       at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
       at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
       at System.Windows.Forms.ComboBox.set_SelectedItem(Object value)
       at NAudioDemo.VolumeMixerDemo.VolumePanel.VolumePanel_Load(Object sender, EventArgs e) in d:\Code\github\NAudio\NAudioDemo\VolumeMixerDemo\VolumePanel.cs:line 97
       at System.Windows.Forms.UserControl.OnLoad(EventArgs e)

This may be a 32 bit vs 64 bit issue as when I try it on Windows 7 as 32 bit I also get an exception. This one is a bit of a weird one though as it comes from Process.MainModule:

    System.ComponentModel.Win32Exception was unhandled
      Message=Only part of a ReadProcessMemory or WriteProcessMemory request was completed
      Source=System
      ErrorCode=-2147467259
      NativeErrorCode=299
      StackTrace:
           at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
           at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
           at System.Diagnostics.Process.get_MainModule()
           at NAudioDemo.VolumeMixerDemo.VolumePanel..ctor(MMDevice device, AudioSessionControl session) in d:\Code\github\NAudio\NAudioDemo\VolumeMixerDemo\VolumePanel.cs:line 73

**Comment by markheath** [comment]
OK, the second exception was just that it didn't like a particular process running on my machine. May be worth protecting the demo against that as all it is trying to do is get hold of the icon. 

And seems to work OK as 32 bit process in Win 7. So just need to work out what is going on in Vista

**Comment by markheath** [comment]
What it looks like you have put the methods from [IAudioSessionManager2](https://msdn.microsoft.com/en-us/library/windows/desktop/dd370950(v=vs.85).aspx) into IAudioSessionManager. Ideally both interfaces should be defined in NAudio, and the features from the 2 interface should only be available on OS that supports it

**Comment by KvanTTT** [comment]
Ok, I'll try to fix it.

**Comment by markheath** [comment]
the same issue will exist with IAudioSessionControl2. Note that inheriting interfaces is a real pain with COM. You usually have to redefine all the methods from the inherited interface (as it is all offset based). See IMFActivate as an example of how this works (basically cut and paste the old interface in and use new keyword on all the v1 methods). 

But all looks good otherwise. This will be a really nice feature for NAudio.

**Comment by markheath** [comment]
just checking in, have you had a chance to look into this?

**Comment by KvanTTT** [comment]
Yes, but unfortunately at present I have not free time to complete it.

**Comment by markheath** [comment]
OK, no problem, it's just that there is now another pull request relating to IAudioStreamVolume, but I'd like to get this one in first if possible, and then see if there is any additional behaviour we need from the other one

**Comment by markheath** [comment]
I think I may have got this working now on Vista. Hopefully will get my changes checked in soon.

**Comment by markheath** [comment]
OK, have merged this in now with fixes so it doesn't crash on Vista. Possibly not the most elegant solution, but seems to work. If you get the chance, please get latest and check that all the behaviour you wanted still works.

**Comment by KvanTTT** [comment]
Ok, it's good. I'll check it. On first sight you forgot to check some warnings (Inherited member hiding. Correct way is using "new" keyword for appropriate members).

**Comment by markheath** [comment]
doh, forgot to check the warnings. Also had to do a fix-up to the Win8 project too.

**Pull request merged**
