### PR TITLE
Add WriteToStream method.

### PR DESCRIPTION
**Pull request by axynos**
Add a method that outputs all data from a WaveProvider to a Stream.
Based off of CreateWaveFile, came in useful for me and thought it would be nice to include in NAudio.

### CODE REVIEW

**Comment by markheath** [comment]
nice idea, I wonder if it might be good to name it more similarly to `CreateWaveFile` maybe `CreateWaveStream` or something more descriptive like `WriteWavFileToStream`

**Comment by axynos** [comment]
Well the current method just appends the data to the end, but doesn't create a new stream, so WriteWavFileToStream would probably be more accurate.

**Comment by markheath** [comment]
ok let's go with that then

**Comment by markheath** [comment]
did you mean to close this PR? I can merge it now if you're done

**Comment by axynos** [comment]
closed by accident, whoops :) And yes I'm done.

**Pull request merged**
